### ISSUE TITLE
최초 이슈 타입이 없을 때 자동 생성

### ISSUE THREAD

**Issue by rerewww** [yeen28/voa#26]
[작업 내용]
- 최초 디비를 구축할 때 이슈 타입 테이블에 데이터가 존재하지 않기 때문에 자동으로 추가되는 방법이 필요합니다.

**Comment by yeen28** [comment]
```
  # 최초 DB 구축 시 자동으로 데이터 삽입.
spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: never # DB 최초  구축 시에만 always로 변경
      encoding: UTF-8 # 한글깨짐 방지
```
